# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meandrous Scribe
email: ChristopherRoberts.M@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Meandrous Scribe, the official blog of Chris Roberts: 
  science journalism graduate, general nerd, and Oxford comma user. 
  Here, you can expect to see text, oodles of it, on topics ranging 
  from science and entertainment to opinion and Clojure programming projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.MeandrousScribe.com" # the base hostname & protocol for your site
twitter_username: MeandrousScribe
github_username:  ChristopherRoberts-M

# Build settings
markdown: kramdown
